abilities_translation = {
    'overgrow': 'Supercrescimento',
    'adaptability': 'Adaptabilidade',
    'aftermath': 'Retaliação',
    'air-lock': 'Desfazer',
    'alert': 'Alerta',
    'analytic': 'Analítico',
    'anger-point': 'Ponto de Raiva',
    'anticipation': 'Antecipação',
    'arena-trap': 'Armadilha de Arena',
    'aroma-veil': 'Véu Aromático',
    'as-one': 'Como Um Só',
    'battle-armor': 'Armadura de Batalha',
    'beast-boost': 'Aprimoramento de Fera',
    'berserk': 'Furor',
    'big-pecks': 'Peitos Grandes',
    'blaze': 'Chama',
    'bulletproof': 'À Prova de Balas',
    'cheek-pouch': 'Bolsa das Bochechas',
    'chlorophyll': 'Clorofila',
    'clear-body': 'Corpo Limpo',
    'cloud-nine': 'Nuvem Nove',
    'color-change': 'Mudança de Cor',
    'comatose': 'Comatoso',
    'compound-eyes': 'Olhos Compostos',
    'contrary': 'Contrário',
    'cursed-body': 'Corpo Amaldiçoado',
    'cute-charm': 'Charme Fofo',
    'damp': 'Umidade',
    'dancer': 'Dançarino',
    'dark-aura': 'Aura Sombria',
    'defeatist': 'Derrotista',
    'defiant': 'Desafiador',
    'deflect': 'Desvio',
    'drought': 'Seca',
    'dry-skin': 'Pele Seca',
    'early-bird': 'Coração Madrugador',
    'effect-spore': 'Esporo Efeito',
    'fairy-veil': 'Véu das Fadas',
    'filter': 'Filtro',
    'flame-body': 'Corpo de Chama',
    'flare-blitz': 'Impacto de Chama',
    'flash-fire': 'Fogo de Estalagem',
    'flower-gift': 'Presente Floral',
    'flower-veil': 'Véu Floral',
    'forecast': 'Previsão',
    'forewarn': 'Aviso Previo',
    'friend-guard': 'Guarda do Amigo',
    'frisk': 'Investigador',
    'frozen-skin': 'Pele Congelada',
    'furry-skin': 'Pele Peluda',
    'gluttony': 'Gula',
    'gooey': 'Viscoso',
    'grass-pelt': 'Pelagem de Grama',
    'guts': 'Coragem',
    'harvest': 'Colheita',
    'healer': 'Curandeiro',
    'heat-proof': 'Prova de Calor',
    'honey-gather': 'Coletor de Mel',
    'huge-power': 'Poder Gigante',
    'hustle': 'Correria',
    'ice-body': 'Corpo de Gelo',
    'ice-fang': 'Presas de Gelo',
    'illusion': 'Ilusão',
    'immunity': 'Imunidade',
    'infiltrator': 'Infiltrador',
    'inner-focus': 'Foco Interno',
    'insomnia': 'Insônia',
    'intimidate': 'Intimidação',
    'iron-barbs': 'Espinhos de Ferro',
    'iron-fist': 'Punho de Ferro',
    'justified': 'Justificado',
    'keen-eye': 'Olho Aguçado',
    'leaf-guard': 'Guarda Folha',
    'levitate': 'Levitação',
    'light-metal': 'Metal Leve',
    'lightning-rod': 'Para-Raios',
    'limber': 'Ágil',
    'liquid-ooze': 'Lodo Líquido',
    'magic-guard': 'Proteção Mágica',
    'magma-armor': 'Armadura de Magma',
    'magnet-pull': 'Atração Magnética',
    'marvel-scale': 'Escama Maravilha',
    'mimicry': 'Imitação',
    'minus': 'Menos',
    'mold-breaker': 'Quebra de Molde',
    'moody': 'Humor',
    'multiscale': 'Multiescama',
    'multitype': 'Multitipo',
    'mummy': 'Múmia',
    'natural-cure': 'Cura Natural',
    'no-guard': 'Sem Defesa',
    'normalize': 'Normalizar',
    'oblivious': 'Oblivioso',
    'pickup': 'Pega',
    'pixilate': 'Pixilado',
    'plus': 'Mais',
    'poison-touch': 'Toque Venenoso',
    'pressure': 'Pressão',
    'primordial-sea': 'Mar Primordial',
    'propeller-tail': 'Cauda de Hélice',
    'pure-power': 'Poder Puro',
    'quick-feet': 'Pés Ágeis',
    'rain-dish': 'Bacia da Chuva',
    'rivalry': 'Rivalidade',
    'rock-head': 'Cabeça de Rocha',
    'run-away': 'Fuga',
    'sand-force': 'Força da Areia',
    'sand-rush': 'Corrida da Areia',
    'sand-stream': 'Corrente de Areia',
    'sand-veill': 'Véu da Areia',
    'scrappy': 'Desajeitado',
    'serene-grace': 'Graça Serena',
    'shadow-shield': 'Escudo das Sombras',
    'shed-skin': 'Descamação',
    'simple': 'Simples',
    'skill-link': 'Ligação de Habilidade',
    'slow-start': 'Começo Lento',
    'slush-rush': 'Corrida da Neve',
    'sniper': 'Atirador',
    'snow-cloak': 'Capa de Neve',
    'snow-warning': 'Aviso de Neve',
    'solar-power': 'Poder Solar',
    'solid-rock': 'Pedra Sólida',
    'soul-heart': 'Coração da Alma',
    'speed-boost': 'Aumento de Velocidade',
    'static': 'Estático',
    'steadfast': 'Firmeza',
    'storm-drain': 'Drenagem da Tempestade',
    'strong-jaw': 'Mandíbulas Fortes',
    'sturdy': 'Resistente',
    'suction-cups': 'Ventosas',
    'super-luck': 'Sorte Suprem',
    'swarm': 'Enxame',
    'sweet-veil': 'Véu Doce',
    'symbiosis': 'Simbiose',
    'tank': 'Tanque',
    'tangled-feet': 'Pés Enredados',
    'telepathy': 'Telepatia',
    'teravolt': 'Teravolt',
    'thick-fat': 'Gordura Espessa',
    'torrent': 'Torrent',
    'toxic-boost': 'Aprimoramento Tóxico',
    'trace': 'Rastro',
    'truant': 'Preguiçoso',
    'unaware': 'Desatento',
    'unnerve': 'Perturbação',
    'vital-spirit': 'Espírito Vital',
    'water-absorb': 'Absorve Água',
    'water-compaction': 'Compactação da Água',
    'water-veil': 'Véu da Água',
    'whirlpool': 'Turbilhão',
    'wonder-skin': 'Pele Maravilha',
    'zest': 'Zelo'
}

type_translation = {
    'grass': 'Grama',
    'fire': 'Fogo',
    'water': 'Água',
    'bug': 'Inseto',
    'normal': 'Normal',
    'poison': 'Veneno',
    'electric': 'Elétrico',
    'ground': 'Terra',
    'fairy': 'Fada',
    'fighting': 'Luta',
    'psychic': 'Psíquico',
    'rock': 'Pedra',
    'ice': 'Gelo',
    'dragon': 'Dragão',
    'dark': 'Sombrio',
    'steel': 'Aço',
    'ghost': 'Fantasma',
    'flying': 'Voador',
    'shadow': 'Sombra',
}